# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Install Nix ❄️
      uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
      with:
        # https://github.com/cachix/install-nix-action#inputs
        nix_path: nixpkgs=channel:nixpkgs-unstable

    - name: Build book 📖
      run: nix run nixpkgs#mdbook -- build

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4.9.0
      with:
        # https://github.com/JamesIves/github-pages-deploy-action#configuration-
        clean: true
        folder: book
        token: ${{ secrets.GITHUB_TOKEN }}
