# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v5 # If you're using actions/checkout@v5 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false

    - name: Install Nix
      uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-23.05

    - name: Build book
      run: |
        nix-env -iA mdbook -f '<nixpkgs>'
        mdbook build
